const QUERY_KEYS = {
  AUTHENTICATE: "AUTHENTICATE",
  FAVOURITE_ITEMS: "FAVOURITE_ITEMS",
  RELATIVE_EPISODES: "RELATIVE_EPISODES",
  GENRES: "GENRES",
  PODCASTS: "PODCASTS",
  HOME_FEEDS: "HOME_FEEDS",
  SEARCH_ITEMS: "SEARCH_ITEMS",
  POSTS: "POSTS",
  TOPICS: "TOPICS",
  S_TOPICS: "S_TOPICS",
  POSTS_BY_TOPIC: "POSTS_BY_TOPIC",
  RELATIVE_TOPICS: "RELATIVE_TOPICS",
  RECOMMENDED_TOPICS: "RECOMMENDED_TOPICS",
  POST_LIKES_BY_POST_ID: "POST_LIKES_BY_POST_ID",
  COMMENTS: "COMMENTS",
};

export { QUERY_KEYS };
